### ISSUE TITLE
Basic Project Scaffolding

### ISSUE THREAD

**Issue by ava-cassiopeia** [OwlTechnology/CommandPalette.js#2]
Setup basic project scaffolding.

**Comment by Kiricon** [comment]
Please add Bower integration to project. This requirement was newly written in to the wiki just moments ago.

**Comment by ava-cassiopeia** [comment]
@Kiricon Added a new issue for bower integration: #5

**Comment by ava-cassiopeia** [comment]
Project scaffolding is done, and ready for development.
